version: '3.8'

services:
  scraper:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    volumes:
      - ..:/app
    environment:
      - DATABASE_URL=sqlserver://username:password@db:1433/database_name
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: